export const CREATE_CART_ARRAY = "CREATE_CART_ARRAY";
export const ADD_TO_CART = "ADD_TO_CART";
export const DECREASE_QTY = "DECREASE_QTY";
export const CART_EMPTY = "CART_EMPTY";

export const SAVE_PAYMENT_METHOD = "SAVE_PAYMENT_METHOD";
export const ORDER_PRICES = "ORDER_PRICES";

export const ADD_SHIPPING_ADDRESS = "ADD_SHIPPING_ADDRESS";
export const UPDATE_SHIPPING_ADDRESS = "UPDATE_SHIPPING_ADDRESS";
export const SAVE_SHIPPING_ADDRESS = "SAVE_SHIPPING_ADDRESS";
