export const USER_LOGIN_LOADING = "USER_LOGIN_LOADING";
export const USER_LOGIN_SUCCESSFUL = "USER_LOGIN_SUCCESSFUL";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";

export const USER_REGISTRATION_LOADING = "USER_REGISTRATION_LOADING";
export const USER_REGISTRATION_SUCCESSFUL = "USER_REGISTRATION_SUCCESSFUL";
export const USER_REGISTRATION_ERROR = "USER_REGISTRATION_ERROR";

export const USER_UPDATE_LOADING = "USER_UPDATE_LOADING";
export const USER_UPDATE_SUCCESSFUL = "USER_UPDATE_SUCCESSFUL";
export const USER_UPDATE_ERROR = "USER_UPDATE_ERROR";

export const USER_LOGOUT = "USER_LOGOUT";

//User Verfication Constants
export const USER_REGISTRATION_VERIFICATION_AGAIN_LOADING =
  "USER_REGISTRATION_VERIFICATION_AGAIN_LOADING";
export const USER_REGISTRATION_VERIFICATION_AGAIN_SUCCESSFUL =
  "USER_REGISTRATION_VERIFICATION_AGAIN_SUCCESSFUL";
export const USER_REGISTRATION_VERIFICATION_AGAIN_ERROR =
  "USER_REGISTRATION_VERIFICATION_AGAIN_ERROR";

export const USER_REGISTRATION_VERIFICATION_LOADING =
  "USER_REGISTRATION_VERIFICATION_LOADING";
export const USER_REGISTRATION_VERIFICATION_SUCCESSFUL =
  "USER_REGISTRATION_VERIFICATION_SUCCESSFUL";
export const USER_REGISTRATION_VERIFICATION_ERROR =
  "USER_REGISTRATION_VERIFICATION_ERROR";
